# include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart' # Generated files
    - 'build/**'    # Build output

  errors:
    invalid_use_of_protected_member: ignore
    missing_return: error # บังคับให้ระบุ return เสมอในฟังก์ชัน
    unused_import: error # ห้ามมี import ที่ไม่ได้ใช้งาน
    dead_code: error # ห้ามมีโค้ดที่ไม่ได้ใช้งาน

linter:
  rules:
    always_specify_types: true # ระบุชนิดข้อมูลทุกครั้ง
    annotate_overrides: true # ใส่ @override เสมอ
    avoid_classes_with_only_static_members: true # หลีกเลี่ยงการใช้ class ที่มีแต่ static อย่างเดียว
    avoid_print: true # ห้ามใช้ print ควรใช้ logger แทน
    prefer_const_constructors: true # ใช้ const ทุกครั้งที่เป็นไปได้
    prefer_const_literals_to_create_immutables: true # ใช้ const ใน literal เช่น list, map
    prefer_final_fields: true # ใช้ final แทน var หากค่าไม่เปลี่ยน
    prefer_single_quotes: true # ใช้ single quote เป็นหลัก
    sort_child_properties_last: true # เรียง properties ใน widget ให้ children อยู่ท้ายสุด
    use_key_in_widget_constructors: true # ใส่ key ใน widget constructor เสมอ
    unnecessary_this: true # ลดการใช้ this ที่ไม่จำเป็น
    lines_longer_than_80_chars: false # ยอมให้มีบรรทัดยาวเกิน 80 ตัวอักษรในบางกรณี
